Update contact_monitoring.md
mautic/documentation pull request #345
Opened 2019-10-05 18:16 UTC by PierreAmmeloot

Correct typo

2019-10-07 07:02 UTC, npracht approved these changes

2019-10-07 07:03 UTC, npracht requested changes

2019-10-07 07:03 UTC, npracht commented on fr/contacts/contact_monitoring.md
> +Depuis la version 2.2.0, mt() supporte 2 callbacks, `onload` et `onerror` accepté comme 4éme argument. La méthode `onload` sera exécutée une fois que le pixel de tracking est chargé. Si le chargement
.

2020-04-02 16:40 UTC, closed without merging

2020-04-28 08:36 UTC, PierreAmmeloot reviewed
@RCheesley can you merge this PR?

2020-04-28 10:55 UTC, RCheesley commented
Sorry we can't as we now have re-platformed to another tool for the docs
and this repository is no longer being maintained.  See docs.mautic.org /
github.com/mautic/mautic-documentation

Ruth Cheesley (she/her)

ACQUIA

Mautic Community Manager

p: +44 (0)1442 734282 | m: +44 (0) 7308 164475 | e: ruth.cheesley@acquia.com

/ WE ARE THE OPEN SOURCE DIGITAL EXPERIENCE COMPANY.
<https://www.acquia.com/>


On Tue, 28 Apr 2020 at 09:36, Pierre Ammeloot <notifications@github.com>
wrote:

> *@PierreAmmeloot* commented on this pull request.
>
> @RCheesley <https://github.com/RCheesley> can you merge this PR?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/mautic/documentation/pull/345#pullrequestreview-401617002>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAWLPIJIEKIJLBTBAGARS6DRO2IQZANCNFSM4I5YY7NA>
> .
>