Zapier OAuth2 Docs update
mautic/documentation pull request #375
Opened 2020-02-14 09:58 UTC by kuzmany

https://github.com/mautic/mautic-zapier/pull/18

2020-02-14 09:59 UTC, RCheesley commented on en/plugins/zapier.md
> +New version of app improve authentication by Oauth2 protocol.
This new version of the app improves authentication by implementing the Oauth2 protocol

2020-02-14 10:00 UTC, RCheesley commented on en/plugins/zapier.md
> +![How to enable API](https://user-images.githubusercontent.com/462477/74520415-cc616b00-4f17-11ea-8dbe-f6dd8a0a6cfc.png)
How to enable the API

2020-02-14 10:00 UTC, RCheesley commented on en/plugins/zapier.md
> + If you're using Zapier 2.x, this Zapier integration use Basic Authentication to access Mautic API. It is disabled by default so enable this first.
If you are using Zapier 2.x, Basic Authentication is used to access the Mautic API. This is disabled by default, so you will need to enable it first.

2020-02-14 10:01 UTC, RCheesley commented on en/plugins/zapier.md
> +Once you choose to use Mautic integration you'll need to authorize your Mautic to it.
Once you choose to enable the integration, you will need to authorize Mautic to communicate with Zapier.

2020-02-14 10:03 UTC, RCheesley requested changes
I've made a few minor suggestions - please also take a look at https://github.com/mautic/documentation/blob/master/CONTRIBUTING.md for our guidelines on documentation and give me a shout if anything is unclear!

2020-02-14 10:04 UTC, kuzmany commented
@RCheesley I see. Thanks

2020-02-14 10:07 UTC, kuzmany commented
@escopecz How we handle with basic auth info. Should remove it, or just notice about changes from basic auth to oauth. Or let setup also for 2.x (basic auth) and 3.x (oauth2) separately

2020-02-14 16:02 UTC, escopecz commented
I guess we can remove it. The question is whether we want to wait with the Zapier Oauth2 PR till we fix the refresh token expiration or add to the docs to increase the refresh token lifetime to some big number.

2020-02-24 14:51 UTC, kuzmany commented
@escopecz that refresh token expiration should be updated on every access token generate. That means, app stop working just If there is no usage during that expiration (default 14 days). Should we add just note to docs?

2020-02-24 14:57 UTC, escopecz commented
@kuzmany you don't sound confident :) You said a customer of yours already runs this version. There are no problems with timeouts? Is their expiration value default at the Mautic API configuration?

A note in the docs would be great.

2020-02-24 15:01 UTC, kuzmany commented
@escopecz It was bug, we didn't store updated refresh_token. But at the moment looks good. I did few tests

2020-10-07 05:30 UTC, closed without merging